import { query } from '../../db/pool.js';
import { queueNotification } from '../notifications/service.js';
import { publishDomainEvent } from '../integrations/event-bus.js';
async function upsertAlert(input:{type:string;severity:'INFO'|'WARNING'|'HIGH'|'CRITICAL';orderId?:string|null;vendorId?:string|null;deliveryPartnerId?:string|null;targetUserId?:string|null;title:string;message:string;metadata?:Record<string,unknown>;dedupeKey:string}) {
 const r=await query<{id:string;is_new:boolean}>(`INSERT INTO operational_alerts(alert_type,severity,order_id,vendor_id,delivery_partner_id,target_user_id,title,message,metadata,dedupe_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(dedupe_key) DO UPDATE SET severity=EXCLUDED.severity,last_detected_at=NOW(),updated_at=NOW(),status=CASE WHEN operational_alerts.status='RESOLVED' THEN 'OPEN' ELSE operational_alerts.status END RETURNING id,(xmax=0) AS is_new`,[input.type,input.severity,input.orderId??null,input.vendorId??null,input.deliveryPartnerId??null,input.targetUserId??null,input.title,input.message,JSON.stringify(input.metadata??{}),input.dedupeKey]);
 const id=r.rows[0]?.id;if(!id)return null;if(r.rows[0]?.is_new&&input.targetUserId)await queueNotification({userId:input.targetUserId,channel:'PUSH',title:input.title,body:input.message,data:{type:'OPERATIONAL_ALERT',alertId:id,orderId:input.orderId??''}});if(r.rows[0]?.is_new)await publishDomainEvent({type:'OPERATIONAL_ALERT_CREATED',aggregateType:'operational_alert',aggregateId:id,payload:{alertType:input.type,severity:input.severity,orderId:input.orderId??null}});return id;
}
export async function runOperationalAlertAutomation(){let created=0;
 const stuck=await query<{id:string;status:string;vendor_id:string;owner_user_id:string|null;customer_code:string}>(`SELECT o.id,o.status,o.vendor_id,v.owner_user_id,cp.customer_code FROM orders o JOIN vendors v ON v.id=o.vendor_id JOIN customer_profiles cp ON cp.user_id=o.customer_id WHERE o.status IN ('PAID','COD_CONFIRMED','VENDOR_ACCEPTED','PREPARING') AND o.created_at < NOW()-INTERVAL '25 minutes' LIMIT 200`);
 for(const o of stuck.rows){const id=await upsertAlert({type:'VENDOR_ORDER_STALLED',severity:'HIGH',orderId:o.id,vendorId:o.vendor_id,targetUserId:o.owner_user_id,title:'Order needs attention',message:`Order ${o.customer_code} has remained in ${o.status} for over 25 minutes.`,metadata:{status:o.status},dedupeKey:`VENDOR_ORDER_STALLED:${o.id}:${o.status}`});if(id)created++;}
 const unassigned=await query<{id:string;vendor_id:string}>(`SELECT o.id,o.vendor_id FROM orders o LEFT JOIN delivery_assignments da ON da.order_id=o.id WHERE o.status IN ('READY_FOR_PICKUP','DELIVERY_ASSIGNED') AND da.id IS NULL AND o.updated_at < NOW()-INTERVAL '10 minutes' LIMIT 200`);
 const admins=await query<{id:string}>(`SELECT id FROM users WHERE role IN ('SUPER_ADMIN','ADMIN','OPS_ADMIN') LIMIT 50`);
 for(const o of unassigned.rows)for(const a of admins.rows){const id=await upsertAlert({type:'DELIVERY_UNASSIGNED',severity:'CRITICAL',orderId:o.id,vendorId:o.vendor_id,targetUserId:a.id,title:'Delivery assignment overdue',message:'An order has been waiting for delivery assignment for more than 10 minutes.',dedupeKey:`DELIVERY_UNASSIGNED:${o.id}:${a.id}`});if(id)created++;}
 const provider=await query<{id:string;order_id:string;status:string;provider_status:string|null}>(`SELECT id,order_id,status,provider_status FROM provider_reconciliation_items WHERE status IN ('AMOUNT_MISMATCH','NO_PROVIDER_RECORD','ERROR') AND created_at>=NOW()-INTERVAL '1 hour' LIMIT 100`);
 const finance=await query<{id:string;order_id:string;item_type:string}>(`SELECT id,order_id,item_type FROM finance_reconciliation_items WHERE status='MISMATCH' AND created_at>=NOW()-INTERVAL '1 hour' LIMIT 100`);
 const financeAdmins=await query<{id:string}>(`SELECT id FROM users WHERE role IN ('SUPER_ADMIN','ADMIN','FINANCE_ADMIN','OPS_ADMIN') LIMIT 50`);
 for(const p of provider.rows)for(const a of financeAdmins.rows){const id=await upsertAlert({type:'PROVIDER_RECONCILIATION_EXCEPTION',severity:'HIGH',orderId:p.order_id,targetUserId:a.id,title:'Payment provider exception',message:`Cashfree reconciliation requires review for payment ${p.id}.`,metadata:{status:p.status,providerStatus:p.provider_status},dedupeKey:`PROVIDER_EXCEPTION:${p.id}:${a.id}`});if(id)created++;}
 for(const f of finance.rows)for(const a of financeAdmins.rows){const id=await upsertAlert({type:'FINANCE_RECONCILIATION_MISMATCH',severity:'HIGH',orderId:f.order_id,targetUserId:a.id,title:'Finance reconciliation mismatch',message:`${f.item_type} does not match the ledger expectation for an order.`,dedupeKey:`FINANCE_MISMATCH:${f.id}:${a.id}`});if(id)created++;}
 return {created};}
