import 'package:flutter/material.dart';
import '../../app_controller.dart';
import '../../core/api/aaspass_api.dart';
import '../../core/widgets/ui.dart';
import '../../models/domain.dart';

class StoreScreen extends StatefulWidget{const StoreScreen({required this.vendorId,required this.cart,this.vendor,super.key});final String vendorId;final CartController cart;final Vendor? vendor;@override State<StoreScreen> createState()=>_StoreScreenState();}
class _StoreScreenState extends State<StoreScreen>{late Vendor vendor;List<Product> products=const [];bool loading=true;String selected='All';@override void initState(){super.initState();vendor=widget.vendor??Vendor(id:widget.vendorId,name:'AasPass Store',category:'Local store',image:'assets/vendors/vendor_daily.png',rating:0,ratingCount:0,lat:0,lng:0,prepMinutes:10,open:true,area:'Nearby',tags:const[]);_load();}
Future<void> _load()async{try{final list=await AasPassApi.instance.vendorProducts(widget.vendorId);if (mounted) {
  setState(() {
    products = list.map((j) => Product.fromJson({...j, 'image': _image('${j['name']} ${j['category_name'] ?? ''}')})).toList();
    loading = false;
  });
}}catch(_){if(mounted)setState(()=>loading=false);}}
String _image(String text){final t=text.toLowerCase();if(t.contains('chip'))return 'assets/products/chips.png';if(t.contains('bhujia')||t.contains('namkeen'))return 'assets/products/bhujia.png';if(t.contains('milk'))return 'assets/products/milk.png';if(t.contains('banana'))return 'assets/products/banana.png';if(t.contains('soap'))return 'assets/products/soap.png';if(t.contains('clean'))return 'assets/products/cleaner.png';if(t.contains('egg'))return 'assets/products/eggs.png';if(t.contains('cable'))return 'assets/products/cable.png';return 'assets/products/atta.png';}
@override Widget build(BuildContext context){final cats=['All',...products.map((p)=>p.category).where((e)=>e.isNotEmpty).toSet()];final visible=selected=='All'?products:products.where((p)=>p.category==selected).toList();return Scaffold(appBar:AppBar(title:Text(vendor.name,style:const TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:CustomScrollView(slivers:[SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,4,16,14),child:ClipRRect(borderRadius:BorderRadius.circular(20),child:SizedBox(height:170,child:Stack(fit:StackFit.expand,children:[Image.asset(vendor.image,fit:BoxFit.cover),Positioned.fill(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(colors:[Colors.transparent,Colors.black.withValues(alpha:.65)],begin:Alignment.topCenter,end:Alignment.bottomCenter)))),Positioned(left:16,bottom:14,right:16,child:Row(children:[Expanded(child:Text(vendor.area,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700))),Text('${vendor.rating.toStringAsFixed(1)} ★',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900))]))]))))),SliverToBoxAdapter(child:SizedBox(height:50,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,itemCount:cats.length,separatorBuilder:(_,_)=>const SizedBox(width:8),itemBuilder:(_,i)=>ChoiceChip(label:Text(cats[i]),selected:selected==cats[i],onSelected:(_)=>setState(()=>selected=cats[i]))))),SliverPadding(padding:const EdgeInsets.all(16),sliver:SliverGrid(delegate:SliverChildBuilderDelegate((_,i)=>ProductCard(product:visible[i],cart:widget.cart),childCount:visible.length),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:278))) ])));}
}
