import { query } from '../../db/pool.js';
import { getCashfreePayments, cashfreeConfigured } from '../payment/cashfree.js';

export async function reconcileFinance(createdBy:string|null=null){
 const run=(await query<{id:string}>(`INSERT INTO finance_reconciliation_runs(run_type,created_by) VALUES('PLATFORM_REVENUE',$1) RETURNING id`,[createdBy])).rows[0]!;
 let checked=0,matched=0,mismatch=0;
 try {
  const orders=await query<{id:string;platform_fee_paise:string;platform_gst_paise:string}>(`SELECT id,platform_fee_paise,platform_gst_paise FROM orders WHERE status IN ('PAID','COD_CONFIRMED','VENDOR_ACCEPTED','PREPARING','READY_FOR_PICKUP','DELIVERY_ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED') AND created_at>=NOW()-INTERVAL '90 days' ORDER BY created_at DESC LIMIT 1000`);
  for(const o of orders.rows){checked++; for(const [type,expected] of [['PLATFORM_FEE',Number(o.platform_fee_paise)],['PLATFORM_GST',Number(o.platform_gst_paise)]] as const){const r=await query<{amount_paise:string}>(`SELECT COALESCE(SUM(amount_paise),0)::text amount_paise FROM ledger_entries WHERE order_id=$1 AND entry_type=$2 AND direction='CREDIT'`,[o.id,type]);const observed=Number(r.rows[0]?.amount_paise??0);const ok=observed===expected;if(ok)matched++;else mismatch++;await query(`INSERT INTO finance_reconciliation_items(run_id,order_id,item_type,expected_paise,observed_paise,status,details) VALUES($1,$2,$3,$4,$5,$6,$7)`,[run.id,o.id,type,expected,observed,ok?'MATCH':'MISMATCH',JSON.stringify({source:'orders_vs_ledger'})]);}}
  await query(`UPDATE finance_reconciliation_runs SET status='COMPLETED',finished_at=NOW(),checked_count=$2,matched_count=$3,mismatch_count=$4,summary=$5 WHERE id=$1`,[run.id,checked,matched,mismatch,JSON.stringify({windowDays:90})]);
  return {runId:run.id,status:'COMPLETED',checked,matched,mismatch};
 } catch(e){await query(`UPDATE finance_reconciliation_runs SET status='FAILED',finished_at=NOW(),summary=$2 WHERE id=$1`,[run.id,JSON.stringify({error:e instanceof Error?e.message:'Unknown error'})]);throw e;}
}

function normalizeProviderPayments(raw:unknown){const list=Array.isArray(raw)?raw:(raw&&typeof raw==='object'&&Array.isArray((raw as any).data)?(raw as any).data:[]);return list.map((x:any)=>({status:String(x.payment_status??x.paymentStatus??x.status??'').toUpperCase(),amountPaise:x.payment_amount!=null?Math.round(Number(x.payment_amount)*100):x.amount_paise!=null?Number(x.amount_paise):null,id:x.cf_payment_id??x.payment_id??null}));}
export async function reconcileCashfreePayments(createdBy:string|null=null){
 if(!cashfreeConfigured()) throw new Error('CASHFREE_NOT_CONFIGURED');
 const run=(await query<{id:string}>(`INSERT INTO provider_reconciliation_runs(provider,created_by) VALUES('CASHFREE',$1) RETURNING id`,[createdBy])).rows[0]!;
 let checked=0,updated=0,mismatch=0;
 try{
  const payments=await query<{id:string;order_id:string;status:string;amount_paise:string;provider_order_id:string|null}>(`SELECT id,order_id,status,amount_paise,provider_order_id FROM payments WHERE provider='CASHFREE' AND status IN ('PENDING','CREATED') AND created_at>=NOW()-INTERVAL '7 days' ORDER BY created_at ASC LIMIT 100`);
  for(const p of payments.rows){checked++;try{const raw=await getCashfreePayments(p.provider_order_id||p.order_id);const provider=normalizeProviderPayments(raw)[0];if(!provider){mismatch++;await query(`INSERT INTO provider_reconciliation_items(run_id,payment_id,order_id,provider,local_status,status,details) VALUES($1,$2,$3,'CASHFREE',$4,'NO_PROVIDER_RECORD',$5)`,[run.id,p.id,p.order_id,p.status,JSON.stringify({providerOrderId:p.provider_order_id})]);continue;}const amountMismatch=provider.amountPaise!=null&&provider.amountPaise!==Number(p.amount_paise);if(amountMismatch){mismatch++;}let target=p.status;if(['SUCCESS','PAID','COMPLETED'].includes(provider.status))target='PAID';else if(['FAILED','CANCELLED','USER_DROPPED'].includes(provider.status))target='FAILED';if(target!==p.status&&!amountMismatch){await query(`UPDATE payments SET status=$1::payment_status,provider_payment_id=COALESCE($2,provider_payment_id),updated_at=NOW() WHERE id=$3`,[target,provider.id,p.id]);updated++;}await query(`INSERT INTO provider_reconciliation_items(run_id,payment_id,order_id,provider,local_status,provider_status,amount_paise,provider_amount_paise,status,details) VALUES($1,$2,$3,'CASHFREE',$4,$5,$6,$7,$8,$9)`,[run.id,p.id,p.order_id,p.status,provider.status,Number(p.amount_paise),provider.amountPaise,amountMismatch?'AMOUNT_MISMATCH':target===p.status?'MATCH':'UPDATED',JSON.stringify({providerPaymentId:provider.id})]);}catch(e){mismatch++;await query(`INSERT INTO provider_reconciliation_items(run_id,payment_id,order_id,provider,local_status,status,details) VALUES($1,$2,$3,'CASHFREE',$4,'ERROR',$5)`,[run.id,p.id,p.order_id,p.status,JSON.stringify({error:e instanceof Error?e.message:'Unknown error'})]);}}
  await query(`UPDATE provider_reconciliation_runs SET status='COMPLETED',finished_at=NOW(),checked_count=$2,updated_count=$3,mismatch_count=$4,summary=$5 WHERE id=$1`,[run.id,checked,updated,mismatch,JSON.stringify({windowDays:7})]);return{runId:run.id,status:'COMPLETED',checked,updated,mismatch};
 }catch(e){await query(`UPDATE provider_reconciliation_runs SET status='FAILED',finished_at=NOW(),summary=$2 WHERE id=$1`,[run.id,JSON.stringify({error:e instanceof Error?e.message:'Unknown error'})]);throw e;}
}
