import 'package:flutter/material.dart';
import '../../core/api/aaspass_api.dart';
import '../../core/theme/app_theme.dart';

class GrowthScreen extends StatefulWidget { const GrowthScreen({super.key}); @override State<GrowthScreen> createState()=>_GrowthScreenState(); }
class _GrowthScreenState extends State<GrowthScreen>{
 bool loading=true; int points=0,lifetime=0; String code='—'; List<Map<String,dynamic>> events=[]; Map<String,dynamic>? membership; List<Map<String,dynamic>> plans=[];
 @override void initState(){super.initState();_load();}
 Future<void> _load() async {try{final l=await AasPassApi.instance.loyalty();final r=await AasPassApi.instance.referral();final m=await AasPassApi.instance.membership();final p=await AasPassApi.instance.membershipPlans();if(mounted)setState((){final a=l['account'];points=int.tryParse('${a is Map?a['points']:0}')??0;lifetime=int.tryParse('${a is Map?a['lifetime_earned']:0}')??0;code='${r['referralCode']??'—'}';events=r['events'] is List?r['events'].whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];membership=m['membership'] is Map?Map<String,dynamic>.from(m['membership']):null;plans=p;loading=false;});}catch(e){if(mounted)setState(()=>loading=false);}}
 Future<void> _redeem() async {if(points<100)return;final used=(points~/100)*100;try{final r=await AasPassApi.instance.redeemLoyalty(points:used,idempotencyKey:'LOYALTY-REDEEM-${DateTime.now().microsecondsSinceEpoch}');if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('₹${((r['walletCreditPaise']??0)/100).toStringAsFixed(2)} added to your wallet')));_load();}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
 Future<void> _apply() async {final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Apply referral code'),content:TextField(controller:c,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(hintText:'AAS...')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Apply'))]));if(ok==true&&c.text.trim().isNotEmpty){try{await AasPassApi.instance.applyReferral(c.text.trim());if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Referral connected to your account.')));_load();}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}}
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:const Text('AasPass Rewards')),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppTokens.green,AppTokens.greenDark]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('AasPass Points',style:TextStyle(color:Colors.white70)),const SizedBox(height:5),Text('$points',style:const TextStyle(color:Colors.white,fontSize:36,fontWeight:FontWeight.w900)),Text('$lifetime lifetime earned',style:const TextStyle(color:Colors.white70)),const SizedBox(height:14),FilledButton(onPressed:points>=100?_redeem:null,style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:AppTokens.greenDark),child:const Text('Redeem to wallet (100 pts = ₹1)'))]),),const SizedBox(height:14),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:AppTokens.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Invite friends',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Your referral code is stored in the AasPass database.',style:TextStyle(color:AppTokens.muted)),const SizedBox(height:12),Row(children:[Expanded(child:SelectableText(code,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900))),IconButton(onPressed:_apply,icon:const Icon(Icons.person_add_alt_1_rounded))]),Text('${events.length} referral connections',style:const TextStyle(color:AppTokens.muted,fontSize:12))])),const SizedBox(height:16),_MembershipCard(membership:membership,plans:plans,onRefresh:_load),const SizedBox(height:16),const Text('Referral activity',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:8),if(events.isEmpty)const Text('No referrals yet.',style:TextStyle(color:AppTokens.muted))else...events.map((e)=>ListTile(contentPadding:EdgeInsets.zero,title:Text('${e['status']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Reward points: ${e['reward_points']??0}')))])));}
}

class _MembershipCard extends StatelessWidget {
  const _MembershipCard({required this.membership,required this.plans,required this.onRefresh});
  final Map<String,dynamic>? membership; final List<Map<String,dynamic>> plans; final Future<void> Function() onRefresh;
  @override Widget build(BuildContext context){
    final active=membership?['status']=='ACTIVE';
    return Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:active?AppTokens.mint:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:AppTokens.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      Row(children:[const Icon(Icons.workspace_premium_rounded,color:AppTokens.green,size:28),const SizedBox(width:10),Expanded(child:Text(active?'${membership?['plan_name']??'AasPass Plus'}':'AasPass Plus',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))),if(active)const Chip(label:Text('ACTIVE'))]),
      const SizedBox(height:6),Text(active?'Your membership benefits are applied automatically during checkout.':'Unlock member delivery and platform-fee benefits.',style:const TextStyle(color:AppTokens.muted)),
      const SizedBox(height:12),if(!active && plans.isNotEmpty)Wrap(spacing:8,runSpacing:8,children:plans.map((p)=>FilledButton.tonal(onPressed:()async{try{final r=await AasPassApi.instance.startMembership(planId:'${p['id']}');if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['nextAction']=='PROVIDER_CHECKOUT_REQUIRED'?'Membership checkout is ready for provider confirmation.':'Membership request created.')));await onRefresh();}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}},child:Text('Join ${p['name']??'Plus'} · ₹${((int.tryParse('${p['monthly_price_paise']}')??0)/100).toStringAsFixed(0)}/mo'))).toList())
    ]));
  }
}
